### PR TITLE
Feat: Background playback

### PR DESCRIPTION
**Pull request by anilbeesetti**

### CODE REVIEW

**Comment by BierDav** [comment]
Would love this feature. What is blocking it to get merged?

**Comment by anilbeesetti** [comment]
> Would love this feature. What is blocking it to get merged?

It's still a work in progress

**Comment by anilbeesetti** [comment]
Hey @Pentaphon, @BierDav, @TidalMist, @eight04, and anyone else reading this! The background playback feature is a major update and required a lot of code changes. If you could test it out and share any feedback or edge cases you find, it would be really helpful. Here’s the link to the debug APK: [Debug APK](https://github.com/anilbeesetti/nextplayer/actions/runs/11664270861/artifacts/2140725913). Thanks a lot!

**Comment by Pentaphon** [comment]
> If you could test it out and share any feedback or edge cases you find,

@anilbeesetti Just tried it and when I press the headphones icon which I assume to be the background playback button, it just highlights the button and the player just waits for me to put the video in the background by pressing back or home, which works, but isn't immediate. We still need the following things:

1. When you press the background playback button, the player should slide away and go to the notification where only the sound should play, similar to how the player goes to the PIP window when you press the PIP button. 
2. We need an X button to close the notification when we want to close it completely from the notification itself. 

Other than those two issues, it is working well. Haven't had enough time to find any playback bugs yet.

**Comment by eight04** [comment]
Tried it and it works 🎉 

For the headphone button, I think it can be moved to settings as a checkbox "continue playing in the background". So that when enabled, users can use the power button to turn off/on the monitor while playing the video.

**Comment by Pentaphon** [comment]
> For the headphone button, I think it can be moved to settings as a checkbox "continue playing in the background"

Or we can have a setting that lets you select 2 options:

Background Playback:

1. Use Background Playback Button (manual)
2. Always play video in background unless stopped or paused (auto)

**Comment by Pentaphon** [comment]
Can't wait to try out the next release with this long awaited feature.

**Pull request merged**
