### PR TITLE
Fix: Volume gesture not working on some phones

### LINKED ISSUE #637: [BUG] Volume Gesture
**Describe the bug**
Volume Gesture not working on right portion of screen. I have to swipe somewhere near to centre of screen to make it work while brightness gesture works fine on left side. In attached screenshot highlighted area gesture doesn't work.

**Expected behavior**

**Screenshots**

Screenshot_20230926-094140_Next Player~2

**Device info (please complete the following information):**
 - Device: Redmi Note 9 Pro Max
 - Android version: Lineageos 20 Android 13
 - App version: 0.9.0

**Additional context**

### PR DESCRIPTION
**Pull request by anilbeesetti**
- fixes #637

### CODE REVIEW

**Comment by anilbeesetti** [comment]
@Yashraj254 maybe test this apk: https://github.com/anilbeesetti/nextplayer/suites/17141015660/artifacts/979286360. If this doesn't work we can try removing the gesture exclusion check

**Comment by anuraag488** [comment]
> @Yashraj254 maybe test this apk: https://github.com/anilbeesetti/nextplayer/suites/17141015660/artifacts/979286360. If this doesn't work we can try removing the gesture exclusion check

This one working fine if i leave navigation bar area. So I'm fine with this.

**Comment by Yashraj254** [comment]
@anilbeesetti it works fine now.. if we exclude the navigation bar area... its much better than before..

**Comment by anilbeesetti** [comment]
> @anilbeesetti it works fine now.. if we exclude the navigation bar area... its much better than before..

Could you elobrate. What do you mean by exclude the navigation bar area

**Comment by Yashraj254** [comment]
@anilbeesetti the area that is covered by system navigation buttons..
whether i use system navigation buttons or Gestures that portion of screen is excluded..for volume controls

sample

**Comment by anilbeesetti** [comment]
Hey @Yashraj254, @anuraag488. Could you test this fix and let me know is it better or worse: https://github.com/anilbeesetti/nextplayer/suites/17238705412/artifacts/984919972

**Comment by anuraag488** [comment]
> Hey @Yashraj254, @anuraag488. Could you test this fix and let me know is it better or worse: https://github.com/anilbeesetti/nextplayer/suites/17238705412/artifacts/984919972

Previous build was better than this. Volume gesture doesn't work close to navigation bar while previous one is working.

**Comment by Yashraj254** [comment]
> Hey @Yashraj254, @anuraag488. Could you test this fix and let me know is it better or worse: https://github.com/anilbeesetti/nextplayer/suites/17238705412/artifacts/984919972

i don't see any difference, it feels same as earlier just the system nav bar area is excluded.

**Comment by anuraag488** [comment]
Here is video of both builds. There is slight difference in gesture area.

https://github.com/anilbeesetti/nextplayer/assets/7353086/1c2ee724-4951-4582-84af-6968b70346df


https://github.com/anilbeesetti/nextplayer/assets/7353086/a6473095-5715-4960-9508-c02a910d4c95

**Comment by Yashraj254** [comment]
> Here is video of both builds. There is slight difference in gesture area.
> 
>  new.build.mp4 
>  old.build.mp4

its better to use the previous build then..

**Pull request merged**
