### PR TITLE
Feat: Add media info dialog

### PR DESCRIPTION
**Pull request by anilbeesetti**

### CODE REVIEW

**Comment by anilbeesetti** [comment]
@VasilisKos @drogga can you guys test this for crashes, any odd behavior. Here's the debug apk: https://github.com/anilbeesetti/nextplayer/suites/17027132757/artifacts/972431330

**Comment by VasilisKos** [comment]
> @VasilisKos @drogga can you guys test this for crashes, any odd behavior. Here's the debug apk: https://github.com/anilbeesetti/nextplayer/suites/17027132757/artifacts/972431330

Works fine. 👍
Just correct the first letter of the "properties" word to capital. > "Properties" 😉

**Comment by drogga** [comment]
If the MediaInfo is as detailed and full like in the MX Player _(I haven't used it in years, but it looks awesome there & I doubt they ruined that)_, then it would be awesome, because I don't know any other player with as comprehensive content info as MXP.

There should definitely be a button for this while playing (not only in the library, which I don't use or care about) and the "P" should be uppercase.
Speaking of library - since I tested this on a device without any videos on it, it managed to find some in /system/media/weather/, but it only shows 3 of 18 Total in that location (media scanner issue perhaps) and their duration is 8 Sec., but this app shows them as 00:00, in the properties too.
_This is on HTC with A.8.0.0 and I don't care if it lists all 18 of them or only 3, but it's strange._

**Comment by drogga** [comment]
If the MediaInfo is as detailed and full like in the MX Player _(I haven't used it in years, but its dialog pop-up window is with transparency & looks awesome there, I doubt they ruined that)_, then it would be awesome, because I don't know any other player with as comprehensive content info as MXP.

There should definitely be a button for this while playing (not only in the library, which I don't use or care about).
Speaking of library - since I tested this on a device without any videos on it, it managed to find some in /system/media/weather/, but it only shows 3 of 18 Total in that location (media scanner issue perhaps) and their duration is 8 Sec., but this app shows them as 00:00, in the properties too.
_This is on HTC with A.8.0.0 and I don't care if it lists all 18 of them or only 3, but it's strange._

**Comment by drogga** [comment]
If the MediaInfo is as detailed and full like in the MX Player _(I haven't used it in years, but its dialog pop-up window is with transparency & looks awesome there, I doubt they ruined that)_, then it would be awesome, because I don't know any other player with as comprehensive content info as MXP.

There should definitely be a button for this while playing (not only in the library, which I don't use or care about).
Speaking of library - since I tested this on a device without any videos on it, it managed to find some in /system/media/weather/, but it only shows 3 of 18 Total in that location (media scanner issue perhaps) and their duration (runtime) is 8 sec. each, but this app shows them as 00:00, in the properties too.
_This is on HTC with A.8.0.0 and I don't care if it lists all 18 of them or only 3, but it's strange._

**Comment by anilbeesetti** [comment]
@drogga Yeah i will add a button in player to get media info. And secondly that is in fact media scanner issue

**Comment by drogga** [comment]
Hey @anilbeesetti, up to this day, there's still no way/button to see any media info properties during playback, especially when using Next Player from the Open With from a file manager, using URI or whatever..., please add it, as a matter of fact, I've never even seen it, because I never rely on the app's library/gallery to play videos from there, always from a file manager like MT Manager, since it's only available as a context menu entry when not playing a video.

**Pull request merged**
