### PR TITLE
Add support for monochrome icon (Android 13+ only)

### LINKED ISSUE #396: Add monochrome icon
Please support the Android 13 Themed App Icons feature.

### PR DESCRIPTION
**Pull request by milindgoel15**
closes #396 

I was not able to test on a real device as Android Studio won't let me build the project even the debug build due to some ffmpeg error
image

Let me know if the icon needs adjustments or needs to reduce/increase size.

### CODE REVIEW

**Comment by anilbeesetti** [comment]
@milindgoel15, Try rebasing or merging main branch to pull latest changes. It will build now

**Comment by milindgoel15** [comment]
> @milindgoel15, Try rebasing or merging main branch to pull latest changes. It will build now

Yep does now. This is how it will look. What do you think? First one is with stroke width 3 and second is 4. i think 4 is better.

stroke width 3

stroke width 4

**Comment by anilbeesetti** [comment]
Check this: I think it is better, don't you think
screenshot_1690000744

**Comment by milindgoel15** [comment]
Yep filled is okay too.

**Comment by milindgoel15** [comment]
The viewport height and width aren't as per Google android docs. So do make sure ur icon fits perfectly in all devices. 

Different viewports can mess up icons on custom skins like MIUI.

**Comment by anilbeesetti** [comment]
Thanks for the suggestion. So far i didn't encounter any issues with the icon. But i'll look into docs

**Pull request merged**
