### PR TITLE
Refactor: Unlock controls layout

### PR DESCRIPTION
**Pull request by anilbeesetti**

### CODE REVIEW

**Comment by drogga** [comment]
When the controls are locked, the "Unlock" button when shown now is covering over part of the subtitles, the previous button from/in the prev. ver. was a lot better and transparent, I get that you wanted to make it more easily accessible and not being in the top left corner, but it gets in the way now, which is a minor thing, but still...

**Comment by drogga** [comment]
@anilbeesetti
I don't won't to be too persistent to the point of being annoying, but I would really appreciate if you can react (with the "eyes" emoji for example) to the above comment when you read (see) it, in case you don't want to reply. Thank You.

**Comment by anilbeesetti** [comment]
Sorry @drogga. I've been busy lately with something. Unlock controls layout is only visible for 2 seconds and it will automatically hide right, so I don't think it would be a problem for most users.

**Comment by drogga** [comment]
I know, I noticed and I agree that it won't bother most of the users, but I guess my screens on 2 devices the app is installed on are sensitive even without the increased sensitivity enabled, so even when I hover close to the screen while the controls are locked, the "Unlock" button shows up, which is full color, the same thing with SPen (I guess) and that button covers & hides part of the subtitles when watching foreign movies, so I have to unlock to go back a tiny bit with a gesture in order to read the short/fast timing lines, but that can't be that precise, because I've purposely made the double tap gestures to only Play/Pause and there are no seek back/forward buttons, only previous/next video, so that sets me more seconds and sometimes minutes back by mistake, wasting time, when that unlock button can be made a bit transparent like before or moved to the center where it won't interfere with anything, since the rest of the controls, like the paly/pause button are hidden anyway when locked. Actually it won't hurt and it will be better in my opinion if you add back/forward seek buttons and make all the controls (or some of them, like the main / centered ones at least) a bit transparent ~30%, they will still be visible in any scenario I guess, even over a full bright white part of a video.

Maybe I use the player in a bad unexpected way or improperly, but it's still something (a feedback) to consider.

I hope I'm not wasting too much of your time, for which I apologize in advance.

**Comment by anilbeesetti** [comment]
I'll look into it

**Pull request merged**
