### PR TITLE
Fix #431 Added shuffle feature

### LINKED ISSUE #431: [FEATURE] Random play (Shuffle)
Please, add a button on the main screen to play videos of a folder randomly, instead of consecutively.

### PR DESCRIPTION
**Pull request by Yashraj254**
fix #431  Added a Shuffle Button in Media Picker Folder Screen .. clicking on which randomly plays any video from that particular  folder and clicking on next button keeps playing videos in a random order ..

### CODE REVIEW

**Comment by Yashraj254** [comment]
hey, i am new to open source... can you tell me how to run these tests...

**Comment by anilbeesetti** [comment]
Since it is the first pr from you. I need to approve the test runs. By the way thanks for pr. I'll look into it when i have time

**Comment by anilbeesetti** [comment]
Hey @Yashraj254 just run `./gradlew ktlintFormat` to format the code

**Comment by anilbeesetti** [comment]
Hi @Yashraj254, thank you for your interest in contributing to our project!

Before you start working on an issue or adding a new feature, I kindly request that you initiate a discussion first. This will help us avoid duplication of efforts and ensure that the proposed changes align with our project goals.

Feel free to comment on the issue you're interested in or create a new one if you have a feature in mind. This way, i can discuss the best approach together and ensure that your valuable contributions are integrated smoothly into the project.

Thanks again for your support.

**Comment by anilbeesetti** [comment]
Regrettably, this doesn't align with my vision for the project. Therefore, I am contemplating an alternative implementation approach for this feature. I plan on working on this in the upcoming week.

**Comment by Yashraj254** [comment]
Ok, Got it..

**Pull request closed without merging**
