### PR TITLE
feature added: resume last playback

### LINKED ISSUE #687: [Feat] Resume Last Playback Button
Resume Playback Button on Home Screen to resume last left media.

### PR DESCRIPTION
**Pull request by Yashraj254**
Fix #687 added resume last playback button

https://github.com/anilbeesetti/nextplayer/assets/52420957/122a137a-3dbe-4810-81a4-4800dd313d18

### CODE REVIEW

**Comment by themd0** [comment]
what if the last played video, was streamed from a url ?

**Comment by Yashraj254** [comment]
> what if the last played video, was streamed from a url ?

it will be played from the beginning..

**Comment by themd0** [comment]
> > what if the last played video, was streamed from a url ?
> 
> it will be played from the beginning..

Couldn't find this feature in v0.10.2 but I'm sure you did a geat job

**Comment by Yashraj254** [comment]
> > > what if the last played video, was streamed from a url ?
> > 
> > 
> > it will be played from the beginning..
> 
> Couldn't find this feature in v0.10.2 but I'm sure you did a geat job

i have made the changes long ago it now works for url videos too, last playback video resume from where user left off, but the code is yet to get merged

**Comment by Yashraj254** [comment]
hey @anilbeesetti  conflicts resolved, merge-ready. Appreciate any further feedback or changes.

**Comment by anilbeesetti** [comment]
Thanks @Yashraj254 for your work. I appreciate you for your contributions to this project. I have implemented this in #884 in a different way that also make it possible to mark played and playing videos for each folder. That's why i'm closing this PR. Thanks once agian. And sorry for the late replies

**Pull request closed without merging**
